import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

// frontend component card --- function to cal op

export const products = [
  {
    _id: uuid(),
    brandName: "Ashoka",
    description: "Women's ashoka pink bag",
    categoryName: "Bags",
    img: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "20",
    discountedPrice: 1000,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Gucci",
    description: "Women's black leather hand bag",
    categoryName: "Bags",
    img: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "65",
    discountedPrice: 900,
    rating: 3.7,
  },
  {
    _id: uuid(),
    brandName: "Fendi",
    description: "Brown leather bagpack",
    categoryName: "Bags",
    img: "https://images.unsplash.com/photo-1605733513597-a8f8341084e6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=929&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "40",
    discountedPrice: 8556,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Prada",
    description: "Women's aesthetic light blue bag",
    categoryName: "Bags",
    img: "https://images.unsplash.com/photo-1585218356055-e1bbc5891162?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "5",
    discountedPrice: 800,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Louis Vuitton",
    description: "Women's blue leather handbag",
    categoryName: "Bags",
    img: "https://images.unsplash.com/photo-1575296093822-95cb556a20ec?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: true,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "",
    discountedPrice: 5000,
    rating: 5,
  },
  {
    _id: uuid(),
    brandName: "Fendi",
    description: "Basket Bags",
    categoryName: "Bags",
    img: "https://images.unsplash.com/photo-1554342872-034a06541bad?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women"],
    discount: "3",
    discountedPrice: 500,
    rating: 2,
  },
  {
    _id: uuid(),
    brandName: "Marc Jacobs",
    description: "Black leather bagpack",
    categoryName: "Bags",
    img: "https://images.unsplash.com/photo-1566150908117-e99fa1513af7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "",
    discountedPrice: 765,
    rating: 2.5,
  },
  {
    _id: uuid(),
    brandName: "Chanel",
    description: "Women's blue handbag",
    categoryName: "Bags",
    img: "https://images.unsplash.com/photo-1630396591179-e3753555c502?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "5",
    discountedPrice: 10000,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Ladida",
    description: "Yellow leather handbag",
    categoryName: "Bags",
    img: "https://images.unsplash.com/photo-1608196869764-49434bffc19e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=797&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women"],
    discount: "10",
    discountedPrice: 3000,
    rating: 5,
  },
  {
    _id: uuid(),
    brandName: "Lino Perros",
    description: "Office bag",
    categoryName: "Bags",
    img: "https://images.unsplash.com/photo-1551677399-f38a96cd1bc7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women"],
    discount: "",
    discountedPrice: 6547,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Baggit",
    description: "Kids bag",
    categoryName: "Bags",
    img: "https://images.unsplash.com/photo-1548690593-24c84de8e043?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=874&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Kids"],
    discount: "10",
    discountedPrice: 800,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Everyday Humans",
    description: "Sunscreen",
    categoryName: "Bodycare Products",
    img: "https://images.unsplash.com/photo-1598662972299-5408ddb8a3dc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women"],
    discount: "50",
    discountedPrice: 986,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Lakme",
    description: "Cocooil body lotion",
    categoryName: "Bodycare Products",
    img: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: false,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "35",
    discountedPrice: 400,
    rating: 5,
  },
  {
    _id: uuid(),
    brandName: "Everyday Humans",
    description: "Face sunscreen",
    categoryName: "Bodycare Products",
    img: "https://images.unsplash.com/photo-1598662965554-c00e6ec94925?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    isNewArrival: true,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women"],
    discount: "",
    discountedPrice: 900,
    rating: 1.5,
  },
  {
    _id: uuid(),
    brandName: "Pulp",
    description: "Ultra hydrating moisturiser",
    categoryName: "Bodycare Products",
    img: "https://images.unsplash.com/photo-1629732047847-50219e9c5aef?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women"],
    discount: "80",
    discountedPrice: 1200,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Synchro",
    description: "Moisturiser",
    categoryName: "Bodycare Products",
    img: "https://images.unsplash.com/photo-1548610762-7c6afe24c261?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=876&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men"],
    discount: "95",
    discountedPrice: 6200,
    rating: 4.2,
  },
  {
    _id: uuid(),
    brandName: "Completely Bare",
    description: "Bioglow cosmetic cream",
    categoryName: "Bodycare Products",
    img: "https://images.unsplash.com/photo-1556217256-dcd735bb8711?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women"],
    discount: "",
    discountedPrice: 1500,
    rating: 2.5,
  },
  {
    _id: uuid(),
    brandName: "Curology",
    description: "Curology lips moisturizer",
    categoryName: "Bodycare Products",
    img: "https://images.unsplash.com/photo-1556228852-80b6e5eeff06?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80",
    isNewArrival: true,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "",
    discountedPrice: 1559,
    rating: 3,
  },
  {
    _id: uuid(),
    brandName: "Plum",
    description: "Plum body lovin cream",
    categoryName: "Bodycare Products",
    img: "https://images.unsplash.com/photo-1519735777090-ec97162dc266?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1545&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: false,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women"],
    discount: "10",
    discountedPrice: 1600,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Lotus",
    description: "Fuzz free light weighted cream",
    categoryName: "Bodycare Products",
    img: "https://images.unsplash.com/photo-1594051843837-46cdc08d0d9f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women"],
    discount: "",
    discountedPrice: 799,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Fuzz Free",
    description: "Kids Products",
    categoryName: "Bodycare Products",
    img: "https://images.unsplash.com/photo-1556217257-aa1d0c385e62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Kids"],
    discount: "5",
    discountedPrice: 1499,
    rating: 3.1,
  },
  {
    _id: uuid(),
    brandName: "Durian",
    description: "Green sofa",
    categoryName: "Furniture",
    img: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "10",
    discountedPrice: 1999,
    rating: 5,
  },
  {
    _id: uuid(),
    brandName: "Godrej Interio",
    description: "Golden sofa",
    categoryName: "Furniture",
    img: "https://images.unsplash.com/photo-1577103032015-92adcd22ce22?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=881&q=80",
    isNewArrival: true,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "",
    discountedPrice: 1099,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Usha",
    description: "Regular wooden chair",
    categoryName: "Furniture",
    img: "https://images.unsplash.com/photo-1619389735429-fe80000e7e53?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=761&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "10",
    discountedPrice: 2000,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Usha",
    description: "Wooden Table",
    categoryName: "Furniture",
    img: "https://images.unsplash.com/photo-1611486212355-d276af4581c0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "",
    discountedPrice: 5000,
    rating: 4.1,
  },
  {
    _id: uuid(),
    brandName: "Ikea",
    description: "White chair",
    categoryName: "Furniture",
    img: "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1518&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "50",
    discountedPrice: 50000,
    rating: 5,
  },
  {
    _id: uuid(),
    brandName: "Durian",
    description: "Bed",
    categoryName: "Furniture",
    img: "https://images.unsplash.com/photo-1584132905271-512c958d674a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "50",
    discountedPrice: 25000,
    rating: 5,
  },
  {
    _id: uuid(),
    brandName: "JBL",
    description: "Black wireless headphones",
    categoryName: "Headphones",
    img: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=865&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women"],
    discount: "90",
    discountedPrice: 1100,
    rating: 3.8,
  },
  {
    _id: uuid(),
    brandName: "Sony",
    description: "Classic bluetooth headphones",
    categoryName: "Headphones",
    img: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "",
    discountedPrice: 4000,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Beats",
    description: "Gold beats headphone",
    categoryName: "Headphones",
    img: "https://images.unsplash.com/photo-1484704849700-f032a568e944?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "10",
    discountedPrice: 8756,
    rating: 3,
  },
  {
    _id: uuid(),
    brandName: "Boat",
    description: "Black corded headphone",
    categoryName: "Headphones",
    img: "https://images.unsplash.com/photo-1620360642570-72f7b6a09e01?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1032&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: false,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "20",
    discountedPrice: 2000,
    rating: 3.7,
  },
  {
    _id: uuid(),
    brandName: "Boat",
    description: "Sony wireless headphones",
    categoryName: "Headphones",
    img: "https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "50",
    discountedPrice: 1265,
    rating: 3,
  },
  {
    _id: uuid(),
    brandName: "Diamonds Direct",
    description: "Silver diamond ring",
    categoryName: "Jewellery",
    img: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "50",
    discountedPrice: 100000,
    rating: 5,
  },
  {
    _id: uuid(),
    brandName: "Diamonds Direct",
    description: "Gold color pendant necklace",
    categoryName: "Jewellery",
    img: "https://images.unsplash.com/photo-1569397288884-4d43d6738fbd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=465&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "30",
    discountedPrice: 60000,
    rating: 5,
  },
  {
    _id: uuid(),
    brandName: "H&H Jewels",
    description: "stone studded earrings",
    categoryName: "Jewellery",
    img: "https://images.unsplash.com/photo-1588891825655-aa526b56f805?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "10",
    discountedPrice: 2400,
    rating: 3,
  },
  {
    _id: uuid(),
    brandName: "H&H Jewels",
    description: "Gold and silver artificial earrings",
    categoryName: "Jewellery",
    img: "https://images.unsplash.com/photo-1615655114865-4cc1bda5901e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    isNewArrival: true,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "",
    discountedPrice: 2700,
    rating: 3,
  },
  {
    _id: uuid(),
    brandName: "Jess Jewellers",
    description: "Golden plated ring",
    categoryName: "Jewellery",
    img: "https://images.unsplash.com/photo-1588892239270-bab4a57b4b67?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "30",
    discountedPrice: 2000,
    rating: 3.1,
  },
  {
    _id: uuid(),
    brandName: "Miss Curious",
    description: "Gold touch artificial jewellery",
    categoryName: "Jewellery",
    img: "https://images.unsplash.com/photo-1601121141499-17ae80afc03a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=931&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "10",
    discountedPrice: 1000,
    rating: 2,
  },
  {
    _id: uuid(),
    brandName: "Bohemian",
    description: "Gold touch artificial Bangles",
    categoryName: "Jewellery",
    img: "https://images.unsplash.com/photo-1629118639928-b178ae9ceefc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "15",
    discountedPrice: 875,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Prestige",
    description: "Green, red and yellow plastic spoons",
    categoryName: "Kitchen utensils",
    img: "https://images.unsplash.com/photo-1526434426615-1abe81efcb0b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: false,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men"],
    discount: "",
    discountedPrice: 1500,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Prestige",
    description: "Knife",
    categoryName: "Kitchen utensils",
    img: "https://images.unsplash.com/photo-1593618523725-c22aa27d353d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men"],
    discount: "10",
    discountedPrice: 400,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Ionic Crafters",
    description: "Black and brown mortal and pestle",
    categoryName: "Kitchen utensils",
    img: "https://images.unsplash.com/photo-1611846632212-b54c346bc3b7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men"],
    discount: "15",
    discountedPrice: 600,
    rating: 5,
  },
  {
    _id: uuid(),
    brandName: "Ionic Crafters",
    description: "Silver spoons",
    categoryName: "Kitchen utensils",
    img: "https://images.unsplash.com/photo-1560329649-c952ee843f92?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men"],
    discount: "5",
    discountedPrice: 6000,
    rating: 5,
  },
  {
    _id: uuid(),
    brandName: "Prestige",
    description: "Wooden chopping board",
    categoryName: "Kitchen utensils",
    img: "https://images.unsplash.com/photo-1587411768913-623b76d243c7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men"],
    discount: "20",
    discountedPrice: 1233,
    rating: 3,
  },
  {
    _id: uuid(),
    brandName: "Wellfree",
    description: "Smiley cups",
    categoryName: "Kitchen utensils",
    img: "https://images.unsplash.com/photo-1611274757139-03ff1736701d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1469&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men"],
    discount: "10",
    discountedPrice: 999,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Ceramic",
    description: "Ceramic mugs",
    categoryName: "Kitchen utensils",
    img: "https://images.unsplash.com/photo-1590422886897-7dd50e58577e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men"],
    discount: "",
    discountedPrice: 876,
    rating: 3.8,
  },
  {
    _id: uuid(),
    brandName: "Colorbar",
    description: "Blue and brown makeup brush set",
    categoryName: "Makeup",
    img: "https://images.unsplash.com/photo-1587754256282-a11d04e3472d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "",
    discountedPrice: 5555,
    rating: 3.8,
  },
  {
    _id: uuid(),
    brandName: "Colorbar",
    description: "Cosmetic mockup makeup set",
    categoryName: "Makeup",
    img: "https://images.unsplash.com/photo-1583209814683-c023dd293cc6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "10",
    discountedPrice: 5569,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Loreal",
    description: "Makeup palette",
    categoryName: "Makeup",
    img: "https://images.unsplash.com/photo-1590156424570-698d124ec7dd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "15",
    discountedPrice: 10999,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Maybelline",
    description: "Lipsticks combo set",
    categoryName: "Makeup",
    img: "https://images.unsplash.com/photo-1617422275558-e5f616302690?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: false,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "40",
    discountedPrice: 879,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "M.A.C",
    description: "Miss swiss brush set",
    categoryName: "Makeup",
    img: "https://images.unsplash.com/photo-1631214504157-ee93581cefde?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=725&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: false,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "40",
    discountedPrice: 1599,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Lakme",
    description: "Eyeliner",
    categoryName: "Makeup",
    img: "https://images.unsplash.com/photo-1631237535134-e009a5939d9c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=725&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "",
    discountedPrice: 1299,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Adiddas",
    description: "Cotton cloth masks",
    categoryName: "Masks",
    img: "https://images.unsplash.com/photo-1586942593568-29361efcd571?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: false,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men", "Kids"],
    discount: "",
    discountedPrice: 799,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Adiddas",
    description: "Classic masks",
    categoryName: "Masks",
    img: "https://images.unsplash.com/photo-1586867764343-c1e7ca23b3da?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men", "Kids"],
    discount: "10",
    discountedPrice: 399,
    rating: 2.5,
  },
  {
    _id: uuid(),
    brandName: "Apple",
    description: "Silver iPhone 6",
    categoryName: "Mobiles",
    img: "https://images.unsplash.com/photo-1591337676887-a217a6970a8a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men", "Kids"],
    discount: "20",
    discountedPrice: 55000,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Apple",
    description: "Purple iPhone 7",
    categoryName: "Mobiles",
    img: "https://images.unsplash.com/photo-1591447337751-c7b95cf704ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=744&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men", "Kids"],
    discount: "5",
    discountedPrice: 45000,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Chanel",
    description: "Bleu chanel perfume",
    categoryName: "Perfumes",
    img: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men", "Kids"],
    discount: "5",
    discountedPrice: 5500,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Emporeo",
    description: "Emporeo perfume",
    categoryName: "Perfumes",
    img: "https://images.unsplash.com/photo-1615108395437-df128ad79e80?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men", "Kids"],
    discount: "20",
    discountedPrice: 2500,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "A&M",
    description: "A&M perfume",
    categoryName: "Perfumes",
    img: "https://images.unsplash.com/photo-1627933234009-0f5ce6eb4e3a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=725&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women", "Men", "Kids"],
    discount: "",
    discountedPrice: 4000,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "BharatSthali",
    description: "Plane blue saree",
    categoryName: "Saree",
    img: "https://images.unsplash.com/photo-1610189019389-975bbbc2f8f3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "",
    discountedPrice: 1999,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Desi Butik",
    description: "Yellow saree with green floral print",
    categoryName: "Saree",
    img: "https://images.unsplash.com/photo-1610189000544-1f0885c4bbeb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "",
    discountedPrice: 3409,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Kalanjali",
    description: "Royal blue saree",
    categoryName: "Saree",
    img: "https://images.unsplash.com/photo-1610189012906-4c0aa9b9781e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1474&q=80",
    isNewArrival: true,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "",
    discountedPrice: 2300,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Nike",
    description: "White and blue nike shoes",
    categoryName: "Shoes",
    img: "https://images.unsplash.com/photo-1465453869711-7e174808ace9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=876&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "",
    discountedPrice: 3476,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Reebok",
    description: "Pair of blue and pink",
    categoryName: "Shoes",
    img: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "10",
    discountedPrice: 5889,
    rating: 3.8,
  },
  {
    _id: uuid(),
    brandName: "Jordan",
    description: "Red air jordan 12",
    categoryName: "Shoes",
    img: "https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men"],
    discount: "20",
    discountedPrice: 4873,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Puma",
    description: "Party shoes",
    categoryName: "Shoes",
    img: "https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: false,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men"],
    discount: "5",
    discountedPrice: 8899,
    rating: 5,
  },
  {
    _id: uuid(),
    brandName: "Nike",
    description: "Kids shoes",
    categoryName: "Shoes",
    img: "https://images.unsplash.com/photo-1533681018184-68bd1d883b97?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1031&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Kids"],
    discount: "5",
    discountedPrice: 1287,
    rating: 3.7,
  },
  {
    _id: uuid(),
    brandName: "Sketchers",
    description: "Gray and black shoes",
    categoryName: "Shoes",
    img: "https://images.unsplash.com/photo-1561808843-7adeb9606939?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
    isNewArrival: true,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Kids"],
    discount: "",
    discountedPrice: 3999,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Gucci",
    description: "Black suit",
    categoryName: "Professionals",
    img: "https://images.unsplash.com/photo-1593030103066-0093718efeb9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
    isNewArrival: true,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men"],
    discount: "",
    discountedPrice: 6000,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Nike",
    description: "Black suit jacket",
    categoryName: "Professionals",
    img: "https://images.unsplash.com/photo-1497339100210-9e87df79c218?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: false,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men"],
    discount: "10",
    discountedPrice: 3400,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Titan",
    description: "Blue and silver analog watch",
    categoryName: "Watches",
    img: "https://images.unsplash.com/photo-1609587312208-cea54be969e7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men"],
    discount: "10",
    discountedPrice: 2269,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Titan",
    description: "Women's analog watch",
    categoryName: "Watches",
    img: "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "10",
    discountedPrice: 1279,
    rating: 3,
  },
  {
    _id: uuid(),
    brandName: "Rolex",
    description: "Silver and white analog watch",
    categoryName: "Watches",
    img: "https://images.unsplash.com/photo-1617317376997-8748e6862c01?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men"],
    discount: "20",
    discountedPrice: 3498,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Apple",
    description: "Apple watch",
    categoryName: "Watches",
    img: "https://images.unsplash.com/photo-1461141346587-763ab02bced9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1100&q=80",
    isNewArrival: true,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women"],
    discount: "20",
    discountedPrice: 20000,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Samsung",
    description: "Smart watch",
    categoryName: "Watches",
    img: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women"],
    discount: "20",
    discountedPrice: 15999,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Omega",
    description: "Toy watch",
    categoryName: "Watches",
    img: "https://images.unsplash.com/photo-1579811216948-6f57c19376a5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=396&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Kids"],
    discount: "20",
    discountedPrice: 549,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Quokka",
    description: "Quokka Water Bottles",
    categoryName: "Water Bottles",
    img: "https://images.unsplash.com/photo-1625708458528-802ec79b1ed8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "20",
    discountedPrice: 345,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Fiji",
    description: "Stainless steel Bottle",
    categoryName: "Water Bottles",
    img: "https://images.unsplash.com/photo-1619020986176-50be596d0c02?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
    isNewArrival: true,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "",
    discountedPrice: 899,
    rating: 3,
  },
  {
    _id: uuid(),
    brandName: "Quokka",
    description: "Quokka sqaure Bottles",
    categoryName: "Water Bottles",
    img: "https://images.unsplash.com/photo-1619021016992-07909c5b85d6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "10",
    discountedPrice: 439,
    rating: 3,
  },
  {
    _id: uuid(),
    brandName: "Adiddas",
    description: "Black and white adiddas tumbler",
    categoryName: "Water Bottles",
    img: "https://images.unsplash.com/photo-1606342384762-ddf691b59885?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "10",
    discountedPrice: 987,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Kit And Ace",
    description: "White and silver tube type vape",
    categoryName: "Water Bottles",
    img: "https://images.unsplash.com/photo-1619066045029-5c7e8537bd8c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "30",
    discountedPrice: 999,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Levis",
    description: "Bindle Bottle",
    categoryName: "Water Bottles",
    img: "https://images.unsplash.com/photo-1628498092391-f484db5a0aa3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=876&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men", "Women", "Kids"],
    discount: "10",
    discountedPrice: 2799,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Fashion Q",
    description: "Black shirt",
    categoryName: "Western",
    img: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "10",
    discountedPrice: 475,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Louis Vuitton",
    description: "Grey shirt",
    categoryName: "Western",
    img: "https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "10",
    discountedPrice: 599,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Ralph Lauren",
    description: "White crew neck skirt",
    categoryName: "Western",
    img: "https://images.unsplash.com/photo-1506760105842-74c56599ed06?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "10",
    discountedPrice: 799,
    rating: 4.5,
  },
  {
    _id: uuid(),
    brandName: "Adiddas",
    description: "Women's white long sleeve shirt",
    categoryName: "Western",
    img: "https://images.unsplash.com/photo-1543087903-1ac2ec7aa8c5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=898&q=80",
    isNewArrival: true,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "10",
    discountedPrice: 4500,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Prada",
    description: "Red sweat shirt",
    categoryName: "Western",
    img: "https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: true,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "",
    discountedPrice: 2500,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Gucci",
    description: "Blue washed jacket",
    categoryName: "Western",
    img: "https://images.unsplash.com/photo-1543076447-215ad9ba6923?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men"],
    discount: "",
    discountedPrice: 1999,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Burberry",
    description: "Black play tshirt",
    categoryName: "Western",
    img: "https://images.unsplash.com/photo-1544441893-675973e31985?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: true,
    isInStock: true,
    isInSale: true,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men"],
    discount: "30",
    discountedPrice: 500,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Integrity",
    description: "Grey knit sweater",
    categoryName: "Winter",
    img: "https://images.unsplash.com/photo-1574201635302-388dd92a4c3f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=465&q=80",
    isNewArrival: false,
    hasDiscount: true,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "10",
    discountedPrice: 1500,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Old Navy",
    description: "Grey sweater",
    categoryName: "Winter",
    img: "https://images.unsplash.com/photo-1623197326553-ef361f80e894?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=847&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "",
    discountedPrice: 2200,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Old Navy",
    description: "Yellow coloured fluffy jacket",
    categoryName: "Winter",
    img: "https://images.unsplash.com/photo-1516648064-ee10acfa64db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=863&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men"],
    discount: "",
    discountedPrice: 1200,
    rating: 3.5,
  },
  {
    _id: uuid(),
    brandName: "Floralo",
    description: "Green silk dress",
    categoryName: "Western",
    img: "https://images.unsplash.com/photo-1615584046840-11cbf13c0238?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: false,
    isTrending: false,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Women"],
    discount: "",
    discountedPrice: 1200,
    rating: 4,
  },
  {
    _id: uuid(),
    brandName: "Lofa",
    description: "Pink Men's tshirt",
    categoryName: "Free Style",
    img: "https://images.pexels.com/photos/9558579/pexels-photo-9558579.jpeg",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men"],
    discount: "10",
    discountedPrice: 1000,
    rating: 4.6,
  },
  {
    _id: uuid(),
    brandName: "Lofa",
    description: "Pink Men's tshirt",
    categoryName: "Sunglasses",
    img: "https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    isNewArrival: false,
    hasDiscount: false,
    hasFastDelivery: false,
    isInStock: true,
    isInSale: true,
    isTrending: true,
    isAddedToCart: false,
    isLiked: false,
    isInSection: ["Men"],
    discount: "10",
    discountedPrice: 1000,
    rating: 4.6,
  }
];
