const CLEAR = "CLEAR";
const SORT_BY_PRICE = "SORT_BY_PRICE";
const SORT_BY_RATING = "SORT_BY_RATING";
const SORT_BY_DISCOUNT = "SORT_BY_DISCOUNT";
const FILTER_BY_PRICE = "FILTER_BY_PRICE";
const FILTER_BY_SECTION = "FILTER_BY_SECTION";
const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
const FILTER_BY_PRODUCTS = "FILTER_BY_PRODUCTS";
const FILTER_SEARCHED_PRODUCT = "FILTER_SEARCHED_PRODUCT";

export {
    CLEAR,
    SORT_BY_PRICE,
    SORT_BY_RATING,
    SORT_BY_DISCOUNT,
    FILTER_BY_PRICE,
    FILTER_BY_SECTION,
    FILTER_BY_CATEGORY,
    FILTER_BY_PRODUCTS,
    FILTER_SEARCHED_PRODUCT
};