const MOVE_TO_WISHLIST_FROM_CART = "MOVE_TO_WISHLIST_FROM_CART";
const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";

export {
    MOVE_TO_WISHLIST_FROM_CART,
    ADD_TO_WISHLIST,
    REMOVE_FROM_WISHLIST
};