import { Header } from "./Header/Header";
import { RoutesComponent } from "./Routes/Routes";
import { CategoryType } from "./Category-type/CategoryType";
import { ShopNowImgSection } from "./ShopNowImgSection/ShopNowImgSection";
import { NewArrivalsSection } from "./New-Arrivals/NewArrivalsSection";
import { DiscountedProducts } from "./Discounted-Products/DiscountedProducts";
import { ProductsOnSale } from "./Products-on-sale/ProductsOnSale";
import { Footer } from "./Footer/Footer";
import { SideBar } from "./Side-bar/SideBar";
import { ProductsSection } from "./Products-section/ProductsSection";
import { ProductCard } from "./Product-card/ProductCard";
import { FloatingBtn } from "./Floating-Btn/FloatingBtn";
import { FilterableForm } from "./Filterable-Form/FilterableForm";
import { WishlistProduct } from "./Wishlisted-Product/WishlistedProducts";
import { ProductsInCart } from "./Products-In-Cart/ProductsInCart";
import { LogInCard } from "./LogIn-card/LogInCard";
import { LogOutCard } from "./LogOut-card/LogOutCard";
import { SignUpCard } from "./SignUp-card/SignUpCard";
import { AprizeLogo } from "./Aprize-logo/AprizeLogo";
import { CombinedProvider } from "./Combined-providers/CombinedProviders";
import { FirstVedioCarousel } from "./Carousel/FirstVedioCarousel" ;
import { MainVedio } from "./Carousel/MainVedio";
import { Carousel } from "./Carousel/Carousel";
import { GridTemplate } from "./Grid-template/GridTemplate";

export { Header, RoutesComponent, CategoryType, ShopNowImgSection, NewArrivalsSection, DiscountedProducts, ProductsOnSale, Footer, SideBar, ProductsSection, ProductCard, FloatingBtn, FilterableForm, WishlistProduct, ProductsInCart, LogInCard, LogOutCard, SignUpCard, AprizeLogo, CombinedProvider, FirstVedioCarousel, MainVedio, Carousel, GridTemplate };